all: test

install:
	poetry install

init:
	poetry run python e_commerce/main.py init

clear:
	poetry run python e_commerce/main.py clear

one_transaction:
	poetry run python e_commerce/main.py one_transaction

test:
	poetry run pytest